ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "tipobito" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "natural" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "sexo" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "racacor" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "estciv" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "esc2010" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "ocup" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "lococor" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "linhaa" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "linhab" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "linhac" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "linhad" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "linhaii" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "circobito" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "acidtrab" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "fonte" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "origem" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "esc" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "exame" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "cirurgia" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "causabas_o" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "traffic_casualties"."traffic_datasus_deaths" ALTER COLUMN "causabas" SET DATA TYPE varchar;