// const traffic = pgSchema('traffic_crashes');

// export const accidents = traffic.table(
//   'accidents',
//   {
//     id: serial('id').primaryKey(),
//     protocolo: varchar('protocolo').notNull(),
//     date: date('date').notNull(),
//     time: varchar('time').notNull(),
//     raw_name: text('raw_name').notNull(),
//     name_id: integer('name_id').references(() => pref_street_names.id),
//     natureza: text('natureza_acidente'),
//     situacao: text('situacao'),
//     bairro: varchar('bairro'),
//     endereco: text('endereco'),
//     numero: varchar('numero'),
//     detalhe: text('detalhe_endereco_acidente'),
//     complemento: text('complemento'),
//     bairro_cruz: varchar('bairro_cruzamento'),
//     semaforo: varchar('num_semaforo'),
//     sentido_via: text('sentido_via'),
//     tipo: text('tipo'),
//     auto: integer('auto'),
//     moto: integer('moto'),
//     ciclom: integer('ciclom'),
//     ciclista: integer('ciclista'),
//     pedestre: integer('pedestre'),
//     onibus: integer('onibus'),
//     caminhao: integer('caminhao'),
//     viatura: integer('viatura'),
//     outros: integer('outros'),
//     vitimas: integer('vitimas'),
//     vitimas_fatais: integer('vitimasfatais'),
//     acidente_verificado: boolean('acidente_verificado'),
//     clima: text('tempo_clima'),
//     semaforo_situacao: text('situacao_semaforo'),
//     sinalizacao: text('sinalizacao'),
//     condicao_via: text('condicao_via'),
//     conservacao_via: text('conservacao_via'),
//     ponto_controle: text('ponto_controle'),
//     placa_situacao: text('situacao_placa'),
//     velocidade_max: varchar('velocidade_max_via'),
//     mao_direcao: text('mao_direcao'),
//     divisao_via1: text('divisao_via1'),
//     divisao_via2: text('divisao_via2'),
//     divisao_via3: text('divisao_via3'),
//     created_at: timestamp('created_at').defaultNow(),
//   }
// );
